### ISSUE TITLE
2.3运行崩溃

### ISSUE THREAD

**Issue by LuckyJayce** [desmond1121/RippleCompat#1]
RippleCompat中调用了
v.addOnAttachStateChangeListener(new View.OnAttachStateChangeListener()
这是3.0以上才有的方法

**Comment by desmond1121** [comment]
谢谢指出，我将尽快修复

**Comment by desmond1121** [comment]
@LuckyJayce 我修正了一些2.1中会出现的问题，现在能正常运行了
